// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_logs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (tenant_id, actor_id, action, details)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, actor_id, action, details, created_at, updated_at
`

type CreateAuditLogParams struct {
	TenantID uuid.UUID
	ActorID  uuid.NullUUID
	Action   string
	Details  pqtype.NullRawMessage
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.Action,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllAuditLogs = `-- name: GetAllAuditLogs :many
SELECT id, tenant_id, actor_id, action, details, created_at, updated_at
FROM audit_logs
WHERE tenant_id = $1
`

func (q *Queries) GetAllAuditLogs(ctx context.Context, tenantID uuid.UUID) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAllAuditLogs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, tenant_id, actor_id, action, details, created_at, updated_at
FROM audit_logs
WHERE tenant_id = $1 AND id = $2
`

type GetAuditLogByIDParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetAuditLogByID(ctx context.Context, arg GetAuditLogByIDParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLogByID, arg.TenantID, arg.ID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.Action,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
