// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: buyers.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBuyer = `-- name: CreateBuyer :one
INSERT INTO buyers (tenant_id, name, contact_email)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, contact_email, is_active, created_at, updated_at
`

type CreateBuyerParams struct {
	TenantID     uuid.UUID
	Name         string
	ContactEmail sql.NullString
}

func (q *Queries) CreateBuyer(ctx context.Context, arg CreateBuyerParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, createBuyer, arg.TenantID, arg.Name, arg.ContactEmail)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBuyerUser = `-- name: CreateBuyerUser :one
INSERT INTO buyer_users (tenant_id, buyer_id, user_id)
VALUES ($1, $2, $3)
RETURNING tenant_id, buyer_id, user_id
`

type CreateBuyerUserParams struct {
	TenantID uuid.UUID
	BuyerID  uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) CreateBuyerUser(ctx context.Context, arg CreateBuyerUserParams) (BuyerUser, error) {
	row := q.db.QueryRowContext(ctx, createBuyerUser, arg.TenantID, arg.BuyerID, arg.UserID)
	var i BuyerUser
	err := row.Scan(&i.TenantID, &i.BuyerID, &i.UserID)
	return i, err
}

const deleteBuyer = `-- name: DeleteBuyer :exec
DELETE FROM buyers
WHERE id = $1 AND tenant_id = $2
`

type DeleteBuyerParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteBuyer(ctx context.Context, arg DeleteBuyerParams) error {
	_, err := q.db.ExecContext(ctx, deleteBuyer, arg.ID, arg.TenantID)
	return err
}

const getBuyerByID = `-- name: GetBuyerByID :one
SELECT id, tenant_id, name, contact_email, is_active, created_at, updated_at FROM buyers WHERE id = $1 AND tenant_id = $2
`

type GetBuyerByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetBuyerByID(ctx context.Context, arg GetBuyerByIDParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, getBuyerByID, arg.ID, arg.TenantID)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuyerForUser = `-- name: GetBuyerForUser :one
SELECT buyer_id
FROM buyer_users
WHERE user_id = $1
`

func (q *Queries) GetBuyerForUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getBuyerForUser, userID)
	var buyer_id uuid.UUID
	err := row.Scan(&buyer_id)
	return buyer_id, err
}

const listBuyers = `-- name: ListBuyers :many
SELECT id, tenant_id, name, contact_email, is_active, created_at, updated_at FROM buyers WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListBuyersParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListBuyers(ctx context.Context, arg ListBuyersParams) ([]Buyer, error) {
	rows, err := q.db.QueryContext(ctx, listBuyers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Buyer
	for rows.Next() {
		var i Buyer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ContactEmail,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuyer = `-- name: UpdateBuyer :one
UPDATE buyers
SET name = $3,
	contact_email = $4,
  is_active = $5,
  updated_at = NOW()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, name, contact_email, is_active, created_at, updated_at
`

type UpdateBuyerParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	ContactEmail sql.NullString
	IsActive     sql.NullBool
}

func (q *Queries) UpdateBuyer(ctx context.Context, arg UpdateBuyerParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, updateBuyer,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ContactEmail,
		arg.IsActive,
	)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBuyerStatus = `-- name: UpdateBuyerStatus :exec
UPDATE buyers SET is_active = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateBuyerStatusParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	IsActive sql.NullBool
}

func (q *Queries) UpdateBuyerStatus(ctx context.Context, arg UpdateBuyerStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBuyerStatus, arg.ID, arg.TenantID, arg.IsActive)
	return err
}
