// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaigns.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addSuppressionListToCampaign = `-- name: AddSuppressionListToCampaign :exec
UPDATE campaigns SET suppression_list_id = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type AddSuppressionListToCampaignParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	SuppressionListID uuid.UUID
}

func (q *Queries) AddSuppressionListToCampaign(ctx context.Context, arg AddSuppressionListToCampaignParams) error {
	_, err := q.db.ExecContext(ctx, addSuppressionListToCampaign, arg.ID, arg.TenantID, arg.SuppressionListID)
	return err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (tenant_id, buyer_id, name, delivery_schedule, description, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, buyer_id, suppression_list_id, name, delivery_schedule, is_active, description, start_date, end_date, created_at, updated_at
`

type CreateCampaignParams struct {
	TenantID         uuid.UUID
	BuyerID          uuid.NullUUID
	Name             string
	DeliverySchedule sql.NullString
	Description      sql.NullString
	StartDate        sql.NullTime
	EndDate          sql.NullTime
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.TenantID,
		arg.BuyerID,
		arg.Name,
		arg.DeliverySchedule,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.SuppressionListID,
		&i.Name,
		&i.DeliverySchedule,
		&i.IsActive,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1 AND tenant_id = $2
`

type DeleteCampaignParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) error {
	_, err := q.db.ExecContext(ctx, deleteCampaign, arg.ID, arg.TenantID)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, tenant_id, buyer_id, suppression_list_id, name, delivery_schedule, is_active, description, start_date, end_date, created_at, updated_at FROM campaigns WHERE id = $1 AND tenant_id = $2
`

type GetCampaignByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetCampaignByID(ctx context.Context, arg GetCampaignByIDParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, arg.ID, arg.TenantID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.SuppressionListID,
		&i.Name,
		&i.DeliverySchedule,
		&i.IsActive,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuppressionListForCampaign = `-- name: GetSuppressionListForCampaign :one
SELECT suppression_list_id FROM campaigns WHERE id = $1 AND tenant_id = $2
`

type GetSuppressionListForCampaignParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetSuppressionListForCampaign(ctx context.Context, arg GetSuppressionListForCampaignParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getSuppressionListForCampaign, arg.ID, arg.TenantID)
	var suppression_list_id uuid.UUID
	err := row.Scan(&suppression_list_id)
	return suppression_list_id, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, tenant_id, buyer_id, suppression_list_id, name, delivery_schedule, is_active, description, start_date, end_date, created_at, updated_at FROM campaigns WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCampaignsParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BuyerID,
			&i.SuppressionListID,
			&i.Name,
			&i.DeliverySchedule,
			&i.IsActive,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET
  name = $3,
  buyer_id = $4,
  delivery_schedule = $5,
  is_active = $6,
  description = $7,
  start_date = $8,
  end_date = $9,
  updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, buyer_id, suppression_list_id, name, delivery_schedule, is_active, description, start_date, end_date, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	Name             string
	BuyerID          uuid.NullUUID
	DeliverySchedule sql.NullString
	IsActive         sql.NullBool
	Description      sql.NullString
	StartDate        sql.NullTime
	EndDate          sql.NullTime
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaign,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.BuyerID,
		arg.DeliverySchedule,
		arg.IsActive,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.SuppressionListID,
		&i.Name,
		&i.DeliverySchedule,
		&i.IsActive,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE campaigns SET is_active = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateCampaignStatusParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	IsActive sql.NullBool
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignStatus, arg.ID, arg.TenantID, arg.IsActive)
	return err
}
