// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaign_supplier.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCampaignSupplierRelation = `-- name: CreateCampaignSupplierRelation :one
INSERT INTO campaign_supplier (tenant_id, campaign_id, supplier_id)
VALUES ($1, $2, $3)
RETURNING tenant_id, campaign_id, supplier_id
`

type CreateCampaignSupplierRelationParams struct {
	TenantID   uuid.UUID
	CampaignID uuid.UUID
	SupplierID uuid.UUID
}

func (q *Queries) CreateCampaignSupplierRelation(ctx context.Context, arg CreateCampaignSupplierRelationParams) (CampaignSupplier, error) {
	row := q.db.QueryRowContext(ctx, createCampaignSupplierRelation, arg.TenantID, arg.CampaignID, arg.SupplierID)
	var i CampaignSupplier
	err := row.Scan(&i.TenantID, &i.CampaignID, &i.SupplierID)
	return i, err
}

const deleteCampaignSuppliersByCampaignID = `-- name: DeleteCampaignSuppliersByCampaignID :exec
DELETE FROM campaign_supplier
WHERE campaign_id = $1 AND tenant_id = $2
`

type DeleteCampaignSuppliersByCampaignIDParams struct {
	CampaignID uuid.UUID
	TenantID   uuid.UUID
}

func (q *Queries) DeleteCampaignSuppliersByCampaignID(ctx context.Context, arg DeleteCampaignSuppliersByCampaignIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteCampaignSuppliersByCampaignID, arg.CampaignID, arg.TenantID)
	return err
}

const getAllSuppliersForCampaign = `-- name: GetAllSuppliersForCampaign :many
SELECT supplier_id
FROM campaign_supplier
WHERE tenant_id = $1 AND campaign_id = $2
`

type GetAllSuppliersForCampaignParams struct {
	TenantID   uuid.UUID
	CampaignID uuid.UUID
}

func (q *Queries) GetAllSuppliersForCampaign(ctx context.Context, arg GetAllSuppliersForCampaignParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getAllSuppliersForCampaign, arg.TenantID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var supplier_id uuid.UUID
		if err := rows.Scan(&supplier_id); err != nil {
			return nil, err
		}
		items = append(items, supplier_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaignByIDForSupplier = `-- name: GetCampaignByIDForSupplier :one
SELECT id, tenant_id, buyer_id, suppression_list_id, name, delivery_schedule, is_active, description, start_date, end_date, created_at, updated_at
FROM campaigns
WHERE id = $1
  AND campaigns.tenant_id = $2 AND id IN (
      SELECT campaign_id
      FROM campaign_supplier
      WHERE supplier_id = $3
  )
`

type GetCampaignByIDForSupplierParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	SupplierID uuid.UUID
}

func (q *Queries) GetCampaignByIDForSupplier(ctx context.Context, arg GetCampaignByIDForSupplierParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByIDForSupplier, arg.ID, arg.TenantID, arg.SupplierID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.SuppressionListID,
		&i.Name,
		&i.DeliverySchedule,
		&i.IsActive,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignsForSupplier = `-- name: ListCampaignsForSupplier :many
SELECT id, name, suppression_list_id, is_active, created_at
FROM campaigns
WHERE campaigns.tenant_id = $1 AND campaigns.is_active = TRUE AND
id in (
	SELECT campaign_id
	FROM campaign_supplier
	WHERE supplier_id = $2
)
`

type ListCampaignsForSupplierParams struct {
	TenantID   uuid.UUID
	SupplierID uuid.UUID
}

type ListCampaignsForSupplierRow struct {
	ID                uuid.UUID
	Name              string
	SuppressionListID uuid.UUID
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
}

func (q *Queries) ListCampaignsForSupplier(ctx context.Context, arg ListCampaignsForSupplierParams) ([]ListCampaignsForSupplierRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignsForSupplier, arg.TenantID, arg.SupplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsForSupplierRow
	for rows.Next() {
		var i ListCampaignsForSupplierRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SuppressionListID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
