// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaigns.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const incrementCampaignDeliveredCount = `-- name: IncrementCampaignDeliveredCount :exec
UPDATE campaigns
SET delivered_lead_count = delivered_lead_count + $3,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type IncrementCampaignDeliveredCountParams struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	DeliveredLeadCount int32
}

func (q *Queries) IncrementCampaignDeliveredCount(ctx context.Context, arg IncrementCampaignDeliveredCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementCampaignDeliveredCount, arg.ID, arg.TenantID, arg.DeliveredLeadCount)
	return err
}
