// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delivery_history.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createDeliveryHistory = `-- name: CreateDeliveryHistory :one
INSERT INTO delivery_history (
    tenant_id, job_id, buyer_id, delivery_method_id, status, error_message, payload_summary
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, job_id, buyer_id, delivery_method_id, status, error_message, payload_summary, created_at
`

type CreateDeliveryHistoryParams struct {
	TenantID         uuid.UUID
	JobID            uuid.NullUUID
	BuyerID          uuid.NullUUID
	DeliveryMethodID uuid.NullUUID
	Status           sql.NullString
	ErrorMessage     sql.NullString
	PayloadSummary   pqtype.NullRawMessage
}

func (q *Queries) CreateDeliveryHistory(ctx context.Context, arg CreateDeliveryHistoryParams) (DeliveryHistory, error) {
	row := q.db.QueryRowContext(ctx, createDeliveryHistory,
		arg.TenantID,
		arg.JobID,
		arg.BuyerID,
		arg.DeliveryMethodID,
		arg.Status,
		arg.ErrorMessage,
		arg.PayloadSummary,
	)
	var i DeliveryHistory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.BuyerID,
		&i.DeliveryMethodID,
		&i.Status,
		&i.ErrorMessage,
		&i.PayloadSummary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeliveryHistory = `-- name: DeleteDeliveryHistory :exec
DELETE FROM delivery_history
WHERE id = $1
  AND tenant_id = $2
`

type DeleteDeliveryHistoryParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteDeliveryHistory(ctx context.Context, arg DeleteDeliveryHistoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveryHistory, arg.ID, arg.TenantID)
	return err
}

const getDeliveryHistory = `-- name: GetDeliveryHistory :one
SELECT id, tenant_id, job_id, buyer_id, delivery_method_id, status, error_message, payload_summary, created_at FROM delivery_history
WHERE id = $1
  AND tenant_id = $2
LIMIT 1
`

type GetDeliveryHistoryParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetDeliveryHistory(ctx context.Context, arg GetDeliveryHistoryParams) (DeliveryHistory, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryHistory, arg.ID, arg.TenantID)
	var i DeliveryHistory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.BuyerID,
		&i.DeliveryMethodID,
		&i.Status,
		&i.ErrorMessage,
		&i.PayloadSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listHistoryByJob = `-- name: ListHistoryByJob :many
SELECT id, tenant_id, job_id, buyer_id, delivery_method_id, status, error_message, payload_summary, created_at
FROM delivery_history
WHERE job_id = $1
  AND tenant_id = $2
ORDER BY created_at DESC
`

type ListHistoryByJobParams struct {
	JobID    uuid.NullUUID
	TenantID uuid.UUID
}

func (q *Queries) ListHistoryByJob(ctx context.Context, arg ListHistoryByJobParams) ([]DeliveryHistory, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryByJob, arg.JobID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryHistory
	for rows.Next() {
		var i DeliveryHistory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.BuyerID,
			&i.DeliveryMethodID,
			&i.Status,
			&i.ErrorMessage,
			&i.PayloadSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
