// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deliveries.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteDeliveryByID = `-- name: DeleteDeliveryByID :exec
DELETE FROM deliveries
WHERE id = $1
  AND tenant_id = $2
`

type DeleteDeliveryByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteDeliveryByID(ctx context.Context, arg DeleteDeliveryByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveryByID, arg.ID, arg.TenantID)
	return err
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id, tenant_id, campaign_id, scheduled_at, delivered_at, status, created_at, updated_at, lead_batch_id
FROM deliveries
WHERE id = $1
  AND tenant_id = $2
`

type GetDeliveryByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetDeliveryByID(ctx context.Context, arg GetDeliveryByIDParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryByID, arg.ID, arg.TenantID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.ScheduledAt,
		&i.DeliveredAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeadBatchID,
	)
	return i, err
}

const getDeliveryForCampaign = `-- name: GetDeliveryForCampaign :one
SELECT id, tenant_id, campaign_id, scheduled_at, delivered_at, status, created_at, updated_at, lead_batch_id FROM deliveries
WHERE tenant_id = $1 AND campaign_id = $2
`

type GetDeliveryForCampaignParams struct {
	TenantID   uuid.UUID
	CampaignID uuid.UUID
}

func (q *Queries) GetDeliveryForCampaign(ctx context.Context, arg GetDeliveryForCampaignParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryForCampaign, arg.TenantID, arg.CampaignID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.ScheduledAt,
		&i.DeliveredAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeadBatchID,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, tenant_id, campaign_id, scheduled_at, delivered_at, status, created_at, updated_at, lead_batch_id
FROM deliveries
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR campaign_id = $2)
  AND ($3::text IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT COALESCE($4, 100)
`

type ListDeliveriesParams struct {
	TenantID uuid.UUID
	Column2  uuid.UUID
	Column3  string
	Column4  interface{}
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveries,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CampaignID,
			&i.ScheduledAt,
			&i.DeliveredAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LeadBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleDelivery = `-- name: ScheduleDelivery :one
INSERT INTO deliveries (tenant_id, campaign_id, lead_batch_id, scheduled_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, campaign_id, scheduled_at, delivered_at, status, created_at, updated_at, lead_batch_id
`

type ScheduleDeliveryParams struct {
	TenantID    uuid.UUID
	CampaignID  uuid.UUID
	LeadBatchID uuid.UUID
	ScheduledAt sql.NullTime
}

func (q *Queries) ScheduleDelivery(ctx context.Context, arg ScheduleDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, scheduleDelivery,
		arg.TenantID,
		arg.CampaignID,
		arg.LeadBatchID,
		arg.ScheduledAt,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.ScheduledAt,
		&i.DeliveredAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeadBatchID,
	)
	return i, err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE deliveries
SET status = $3, delivered_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateDeliveryStatusParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Status   sql.NullString
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}
