// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delivery_schedules.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeliverySchedule = `-- name: CreateDeliverySchedule :one
INSERT INTO delivery_schedules (
    id, tenant_id, buyer_id, cron_expression, timezone, is_active, last_run_at, next_run_at
)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, TRUE), $7, $8)
RETURNING id, tenant_id, buyer_id, cron_expression, timezone, is_active, last_run_at, next_run_at, created_at, updated_at
`

type CreateDeliveryScheduleParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BuyerID        uuid.NullUUID
	CronExpression sql.NullString
	Timezone       sql.NullString
	Column6        interface{}
	LastRunAt      sql.NullTime
	NextRunAt      sql.NullTime
}

func (q *Queries) CreateDeliverySchedule(ctx context.Context, arg CreateDeliveryScheduleParams) (DeliverySchedule, error) {
	row := q.db.QueryRowContext(ctx, createDeliverySchedule,
		arg.ID,
		arg.TenantID,
		arg.BuyerID,
		arg.CronExpression,
		arg.Timezone,
		arg.Column6,
		arg.LastRunAt,
		arg.NextRunAt,
	)
	var i DeliverySchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.CronExpression,
		&i.Timezone,
		&i.IsActive,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeliverySchedule = `-- name: DeleteDeliverySchedule :exec
DELETE FROM delivery_schedules
WHERE id = $1
  AND tenant_id = $2
`

type DeleteDeliveryScheduleParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteDeliverySchedule(ctx context.Context, arg DeleteDeliveryScheduleParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeliverySchedule, arg.ID, arg.TenantID)
	return err
}

const getDeliverySchedule = `-- name: GetDeliverySchedule :one
SELECT id, tenant_id, buyer_id, cron_expression, timezone, is_active, last_run_at, next_run_at, created_at, updated_at FROM delivery_schedules
WHERE id = $1
  AND tenant_id = $2
LIMIT 1
`

type GetDeliveryScheduleParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetDeliverySchedule(ctx context.Context, arg GetDeliveryScheduleParams) (DeliverySchedule, error) {
	row := q.db.QueryRowContext(ctx, getDeliverySchedule, arg.ID, arg.TenantID)
	var i DeliverySchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.CronExpression,
		&i.Timezone,
		&i.IsActive,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSchedules = `-- name: ListDueSchedules :many
SELECT id, tenant_id, buyer_id, cron_expression, timezone, is_active, last_run_at, next_run_at, created_at, updated_at
FROM delivery_schedules
WHERE is_active = TRUE
  AND next_run_at <= now()
  AND tenant_id = $1
ORDER BY next_run_at
`

func (q *Queries) ListDueSchedules(ctx context.Context, tenantID uuid.UUID) ([]DeliverySchedule, error) {
	rows, err := q.db.QueryContext(ctx, listDueSchedules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliverySchedule
	for rows.Next() {
		var i DeliverySchedule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BuyerID,
			&i.CronExpression,
			&i.Timezone,
			&i.IsActive,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByBuyer = `-- name: ListSchedulesByBuyer :many
SELECT id, tenant_id, buyer_id, cron_expression, timezone, is_active, last_run_at, next_run_at, created_at, updated_at FROM delivery_schedules
WHERE buyer_id = $1
  AND tenant_id = $2
ORDER BY created_at
`

type ListSchedulesByBuyerParams struct {
	BuyerID  uuid.NullUUID
	TenantID uuid.UUID
}

func (q *Queries) ListSchedulesByBuyer(ctx context.Context, arg ListSchedulesByBuyerParams) ([]DeliverySchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByBuyer, arg.BuyerID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliverySchedule
	for rows.Next() {
		var i DeliverySchedule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BuyerID,
			&i.CronExpression,
			&i.Timezone,
			&i.IsActive,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliverySchedule = `-- name: UpdateDeliverySchedule :one
UPDATE delivery_schedules
SET cron_expression = COALESCE($2, cron_expression),
    timezone = COALESCE($3, timezone),
    is_active = COALESCE($4, is_active),
    last_run_at = COALESCE($5, last_run_at),
    next_run_at = COALESCE($6, next_run_at),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $7
RETURNING id, tenant_id, buyer_id, cron_expression, timezone, is_active, last_run_at, next_run_at, created_at, updated_at
`

type UpdateDeliveryScheduleParams struct {
	ID             uuid.UUID
	CronExpression sql.NullString
	Timezone       sql.NullString
	IsActive       sql.NullBool
	LastRunAt      sql.NullTime
	NextRunAt      sql.NullTime
	TenantID       uuid.UUID
}

func (q *Queries) UpdateDeliverySchedule(ctx context.Context, arg UpdateDeliveryScheduleParams) (DeliverySchedule, error) {
	row := q.db.QueryRowContext(ctx, updateDeliverySchedule,
		arg.ID,
		arg.CronExpression,
		arg.Timezone,
		arg.IsActive,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.TenantID,
	)
	var i DeliverySchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.CronExpression,
		&i.Timezone,
		&i.IsActive,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
