// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delivery_methods.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createDeliveryMethod = `-- name: CreateDeliveryMethod :one
INSERT INTO delivery_methods (
    tenant_id, buyer_id, method_type, config, is_active
)
VALUES ($1, $2, $3, $4, COALESCE($5, TRUE))
RETURNING id, tenant_id, buyer_id, method_type, config, is_active, created_at, updated_at
`

type CreateDeliveryMethodParams struct {
	TenantID   uuid.UUID
	BuyerID    uuid.NullUUID
	MethodType sql.NullString
	Config     json.RawMessage
	Column5    interface{}
}

func (q *Queries) CreateDeliveryMethod(ctx context.Context, arg CreateDeliveryMethodParams) (DeliveryMethod, error) {
	row := q.db.QueryRowContext(ctx, createDeliveryMethod,
		arg.TenantID,
		arg.BuyerID,
		arg.MethodType,
		arg.Config,
		arg.Column5,
	)
	var i DeliveryMethod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.MethodType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeliveryMethod = `-- name: DeleteDeliveryMethod :exec
DELETE FROM delivery_methods
WHERE id = $1
  AND tenant_id = $2
`

type DeleteDeliveryMethodParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteDeliveryMethod(ctx context.Context, arg DeleteDeliveryMethodParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveryMethod, arg.ID, arg.TenantID)
	return err
}

const getDeliveryMethod = `-- name: GetDeliveryMethod :one
SELECT id, tenant_id, buyer_id, method_type, config, is_active, created_at, updated_at FROM delivery_methods
WHERE id = $1
  AND tenant_id = $2
LIMIT 1
`

type GetDeliveryMethodParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetDeliveryMethod(ctx context.Context, arg GetDeliveryMethodParams) (DeliveryMethod, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryMethod, arg.ID, arg.TenantID)
	var i DeliveryMethod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.MethodType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryMethodByBuyerID = `-- name: GetDeliveryMethodByBuyerID :one
SELECT id, tenant_id, buyer_id, method_type, config, is_active, created_at, updated_at FROM delivery_methods
WHERE buyer_id = $1
  AND tenant_id = $2
LIMIT 1
`

type GetDeliveryMethodByBuyerIDParams struct {
	BuyerID  uuid.NullUUID
	TenantID uuid.UUID
}

func (q *Queries) GetDeliveryMethodByBuyerID(ctx context.Context, arg GetDeliveryMethodByBuyerIDParams) (DeliveryMethod, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryMethodByBuyerID, arg.BuyerID, arg.TenantID)
	var i DeliveryMethod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.MethodType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveryMethod = `-- name: UpdateDeliveryMethod :one
UPDATE delivery_methods
SET method_type = COALESCE($2, method_type),
    config = COALESCE($3, config),
    is_active = COALESCE($4, is_active),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $5
RETURNING id, tenant_id, buyer_id, method_type, config, is_active, created_at, updated_at
`

type UpdateDeliveryMethodParams struct {
	ID         uuid.UUID
	MethodType sql.NullString
	Config     json.RawMessage
	IsActive   sql.NullBool
	TenantID   uuid.UUID
}

func (q *Queries) UpdateDeliveryMethod(ctx context.Context, arg UpdateDeliveryMethodParams) (DeliveryMethod, error) {
	row := q.db.QueryRowContext(ctx, updateDeliveryMethod,
		arg.ID,
		arg.MethodType,
		arg.Config,
		arg.IsActive,
		arg.TenantID,
	)
	var i DeliveryMethod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuyerID,
		&i.MethodType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
