// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ActorID   uuid.NullUUID
	Action    string
	Details   pqtype.NullRawMessage
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Buyer struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	ContactEmail sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type BuyerUser struct {
	TenantID uuid.UUID
	BuyerID  uuid.UUID
	UserID   uuid.UUID
}

type Campaign struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	BuyerID           uuid.NullUUID
	SuppressionListID uuid.NullUUID
	Name              string
	DeliverySchedule  sql.NullString
	IsActive          sql.NullBool
	Description       sql.NullString
	StartDate         sql.NullTime
	EndDate           sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type CampaignSupplier struct {
	TenantID   uuid.UUID
	CampaignID uuid.UUID
	SupplierID uuid.UUID
}

type Delivery struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	CampaignID  uuid.UUID
	ScheduledAt sql.NullTime
	DeliveredAt sql.NullTime
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	LeadBatchID uuid.UUID
}

type DeliveryHistory struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	JobID            uuid.NullUUID
	BuyerID          uuid.NullUUID
	DeliveryMethodID uuid.NullUUID
	Status           sql.NullString
	ErrorMessage     sql.NullString
	PayloadSummary   pqtype.NullRawMessage
	CreatedAt        sql.NullTime
}

type DeliveryJob struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	BuyerID          uuid.UUID
	DeliveryMethodID uuid.UUID
	DeliveryID       uuid.NullUUID
	Payload          json.RawMessage
	Description      sql.NullString
	ScheduledAt      time.Time
	DeliveredAt      sql.NullTime
	Status           string
	LastError        sql.NullString
	Attempts         int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type DeliveryMethod struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	BuyerID    uuid.NullUUID
	MethodType sql.NullString
	Config     json.RawMessage
	IsActive   sql.NullBool
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type DeliverySchedule struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BuyerID        uuid.NullUUID
	CronExpression sql.NullString
	Timezone       sql.NullString
	IsActive       sql.NullBool
	LastRunAt      sql.NullTime
	NextRunAt      sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type EmailEvent struct {
	ID             uuid.UUID
	Email          string
	EventType      string
	EventSubtype   sql.NullString
	Reason         sql.NullString
	DiagnosticCode sql.NullString
	FeedbackID     sql.NullString
	MessageID      sql.NullString
	CreatedAt      sql.NullTime
	RawData        pqtype.NullRawMessage
}

type Lead struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	CampaignID          uuid.UUID
	LeadBatchID         uuid.NullUUID
	FirstName           sql.NullString
	LastName            sql.NullString
	EmailCipher         []byte
	PhoneCipher         []byte
	DekWrapped          []byte
	DekKmsKeyID         sql.NullString
	EmailHash           sql.NullString
	PhoneHash           sql.NullString
	IpAddress           pqtype.Inet
	CompanyName         sql.NullString
	Address             sql.NullString
	CountryCode         sql.NullString
	LinkedinContact     sql.NullString
	LinkedinCompany     sql.NullString
	DownloadedAssetName sql.NullString
	PublisherName       sql.NullString
	Industry            sql.NullString
	RevenueSize         sql.NullString
	EmployeeSize        sql.NullString
	Region              sql.NullString
	State               sql.NullString
	Title               sql.NullString
	NaicsCode           sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type LeadBatch struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	CampaignID uuid.UUID
	SupplierID uuid.NullUUID
	BatchName  string
	TotalLeads sql.NullInt32
	Status     sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Supplier struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	ContactEmail sql.NullString
	ApiKey       sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type SupplierUser struct {
	TenantID   uuid.UUID
	SupplierID uuid.UUID
	UserID     uuid.UUID
}

type SuppressionCompany struct {
	ID                uuid.UUID
	SuppressionListID uuid.UUID
	CompanyName       string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type SuppressionEmployeeSize struct {
	ID                uuid.UUID
	SuppressionListID uuid.UUID
	SizeRange         string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type SuppressionEntry struct {
	ID                uuid.UUID
	SuppressionListID uuid.UUID
	NameHash          sql.NullString
	EmailHash         sql.NullString
	PhoneHash         sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type SuppressionList struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type SuppressionRegion struct {
	ID                uuid.UUID
	SuppressionListID uuid.UUID
	RegionName        string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type SuppressionRevenueSize struct {
	ID                uuid.UUID
	SuppressionListID uuid.UUID
	RevenueRange      string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type SuppressionState struct {
	ID                uuid.UUID
	SuppressionListID uuid.UUID
	StateName         string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type Tenant struct {
	ID           uuid.UUID
	Name         string
	ContactEmail sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type User struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	IsActive     sql.NullBool
	Invited      sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
