// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: suppression.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addSuppressionCompany = `-- name: AddSuppressionCompany :one
INSERT INTO suppression_companies (suppression_list_id, company_name)
VALUES ($1, $2)
RETURNING id, suppression_list_id, company_name, created_at, updated_at
`

type AddSuppressionCompanyParams struct {
	SuppressionListID uuid.UUID
	CompanyName       string
}

func (q *Queries) AddSuppressionCompany(ctx context.Context, arg AddSuppressionCompanyParams) (SuppressionCompany, error) {
	row := q.db.QueryRowContext(ctx, addSuppressionCompany, arg.SuppressionListID, arg.CompanyName)
	var i SuppressionCompany
	err := row.Scan(
		&i.ID,
		&i.SuppressionListID,
		&i.CompanyName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addSuppressionEmployeeSize = `-- name: AddSuppressionEmployeeSize :one
INSERT INTO suppression_employee_sizes (suppression_list_id, size_range)
VALUES ($1, $2)
RETURNING id, suppression_list_id, size_range, created_at, updated_at
`

type AddSuppressionEmployeeSizeParams struct {
	SuppressionListID uuid.UUID
	SizeRange         string
}

func (q *Queries) AddSuppressionEmployeeSize(ctx context.Context, arg AddSuppressionEmployeeSizeParams) (SuppressionEmployeeSize, error) {
	row := q.db.QueryRowContext(ctx, addSuppressionEmployeeSize, arg.SuppressionListID, arg.SizeRange)
	var i SuppressionEmployeeSize
	err := row.Scan(
		&i.ID,
		&i.SuppressionListID,
		&i.SizeRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addSuppressionEntry = `-- name: AddSuppressionEntry :one
INSERT INTO suppression_entries (suppression_list_id, email_hash, phone_hash)
VALUES ($1, $2, $3)
RETURNING id, suppression_list_id, email_hash, phone_hash, created_at, updated_at
`

type AddSuppressionEntryParams struct {
	SuppressionListID uuid.UUID
	EmailHash         sql.NullString
	PhoneHash         sql.NullString
}

func (q *Queries) AddSuppressionEntry(ctx context.Context, arg AddSuppressionEntryParams) (SuppressionEntry, error) {
	row := q.db.QueryRowContext(ctx, addSuppressionEntry, arg.SuppressionListID, arg.EmailHash, arg.PhoneHash)
	var i SuppressionEntry
	err := row.Scan(
		&i.ID,
		&i.SuppressionListID,
		&i.EmailHash,
		&i.PhoneHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addSuppressionRegion = `-- name: AddSuppressionRegion :one
INSERT INTO suppression_regions (suppression_list_id, region_name)
VALUES ($1, $2)
RETURNING id, suppression_list_id, region_name, created_at, updated_at
`

type AddSuppressionRegionParams struct {
	SuppressionListID uuid.UUID
	RegionName        string
}

func (q *Queries) AddSuppressionRegion(ctx context.Context, arg AddSuppressionRegionParams) (SuppressionRegion, error) {
	row := q.db.QueryRowContext(ctx, addSuppressionRegion, arg.SuppressionListID, arg.RegionName)
	var i SuppressionRegion
	err := row.Scan(
		&i.ID,
		&i.SuppressionListID,
		&i.RegionName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addSuppressionRevenueSize = `-- name: AddSuppressionRevenueSize :one
INSERT INTO suppression_revenue_sizes (suppression_list_id, revenue_range)
VALUES ($1, $2)
RETURNING id, suppression_list_id, revenue_range, created_at, updated_at
`

type AddSuppressionRevenueSizeParams struct {
	SuppressionListID uuid.UUID
	RevenueRange      string
}

func (q *Queries) AddSuppressionRevenueSize(ctx context.Context, arg AddSuppressionRevenueSizeParams) (SuppressionRevenueSize, error) {
	row := q.db.QueryRowContext(ctx, addSuppressionRevenueSize, arg.SuppressionListID, arg.RevenueRange)
	var i SuppressionRevenueSize
	err := row.Scan(
		&i.ID,
		&i.SuppressionListID,
		&i.RevenueRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addSuppressionState = `-- name: AddSuppressionState :one
INSERT INTO suppression_states (suppression_list_id, state_name)
VALUES ($1, $2)
RETURNING id, suppression_list_id, state_name, created_at, updated_at
`

type AddSuppressionStateParams struct {
	SuppressionListID uuid.UUID
	StateName         string
}

func (q *Queries) AddSuppressionState(ctx context.Context, arg AddSuppressionStateParams) (SuppressionState, error) {
	row := q.db.QueryRowContext(ctx, addSuppressionState, arg.SuppressionListID, arg.StateName)
	var i SuppressionState
	err := row.Scan(
		&i.ID,
		&i.SuppressionListID,
		&i.StateName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSuppressionList = `-- name: CreateSuppressionList :one
INSERT INTO suppression_lists (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, created_at, updated_at
`

type CreateSuppressionListParams struct {
	TenantID    uuid.UUID
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateSuppressionList(ctx context.Context, arg CreateSuppressionListParams) (SuppressionList, error) {
	row := q.db.QueryRowContext(ctx, createSuppressionList, arg.TenantID, arg.Name, arg.Description)
	var i SuppressionList
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSuppressionList = `-- name: DeleteSuppressionList :exec
DELETE FROM suppression_lists 
WHERE tenant_id = $1 AND id = $2
`

type DeleteSuppressionListParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteSuppressionList(ctx context.Context, arg DeleteSuppressionListParams) error {
	_, err := q.db.ExecContext(ctx, deleteSuppressionList, arg.TenantID, arg.ID)
	return err
}

const findSuppressedByEmailHash = `-- name: FindSuppressedByEmailHash :one
SELECT id, suppression_list_id, email_hash, phone_hash, created_at, updated_at
FROM suppression_entries
WHERE suppression_list_id = $1 AND email_hash = $2
LIMIT 1
`

type FindSuppressedByEmailHashParams struct {
	SuppressionListID uuid.UUID
	EmailHash         sql.NullString
}

func (q *Queries) FindSuppressedByEmailHash(ctx context.Context, arg FindSuppressedByEmailHashParams) (SuppressionEntry, error) {
	row := q.db.QueryRowContext(ctx, findSuppressedByEmailHash, arg.SuppressionListID, arg.EmailHash)
	var i SuppressionEntry
	err := row.Scan(
		&i.ID,
		&i.SuppressionListID,
		&i.EmailHash,
		&i.PhoneHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuppressionCompaniesByListID = `-- name: GetSuppressionCompaniesByListID :many
SELECT id, suppression_list_id, company_name, created_at, updated_at
FROM suppression_companies
WHERE suppression_list_id = $1
ORDER BY company_name ASC
`

func (q *Queries) GetSuppressionCompaniesByListID(ctx context.Context, suppressionListID uuid.UUID) ([]SuppressionCompany, error) {
	rows, err := q.db.QueryContext(ctx, getSuppressionCompaniesByListID, suppressionListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuppressionCompany
	for rows.Next() {
		var i SuppressionCompany
		if err := rows.Scan(
			&i.ID,
			&i.SuppressionListID,
			&i.CompanyName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppressionEmployeeSizesByListID = `-- name: GetSuppressionEmployeeSizesByListID :many
SELECT id, suppression_list_id, size_range, created_at, updated_at
FROM suppression_employee_sizes
WHERE suppression_list_id = $1
ORDER BY size_range ASC
`

func (q *Queries) GetSuppressionEmployeeSizesByListID(ctx context.Context, suppressionListID uuid.UUID) ([]SuppressionEmployeeSize, error) {
	rows, err := q.db.QueryContext(ctx, getSuppressionEmployeeSizesByListID, suppressionListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuppressionEmployeeSize
	for rows.Next() {
		var i SuppressionEmployeeSize
		if err := rows.Scan(
			&i.ID,
			&i.SuppressionListID,
			&i.SizeRange,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppressionEntriesByListID = `-- name: GetSuppressionEntriesByListID :many
SELECT id, suppression_list_id, email_hash, phone_hash, created_at, updated_at
FROM suppression_entries
WHERE suppression_list_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSuppressionEntriesByListID(ctx context.Context, suppressionListID uuid.UUID) ([]SuppressionEntry, error) {
	rows, err := q.db.QueryContext(ctx, getSuppressionEntriesByListID, suppressionListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuppressionEntry
	for rows.Next() {
		var i SuppressionEntry
		if err := rows.Scan(
			&i.ID,
			&i.SuppressionListID,
			&i.EmailHash,
			&i.PhoneHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppressionListByID = `-- name: GetSuppressionListByID :one
SELECT id, tenant_id, name, description, created_at, updated_at
FROM suppression_lists
WHERE tenant_id = $1 AND id = $2
`

type GetSuppressionListByIDParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetSuppressionListByID(ctx context.Context, arg GetSuppressionListByIDParams) (SuppressionList, error) {
	row := q.db.QueryRowContext(ctx, getSuppressionListByID, arg.TenantID, arg.ID)
	var i SuppressionList
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuppressionRegionsByListID = `-- name: GetSuppressionRegionsByListID :many
SELECT id, suppression_list_id, region_name, created_at, updated_at
FROM suppression_regions
WHERE suppression_list_id = $1
ORDER BY region_name ASC
`

func (q *Queries) GetSuppressionRegionsByListID(ctx context.Context, suppressionListID uuid.UUID) ([]SuppressionRegion, error) {
	rows, err := q.db.QueryContext(ctx, getSuppressionRegionsByListID, suppressionListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuppressionRegion
	for rows.Next() {
		var i SuppressionRegion
		if err := rows.Scan(
			&i.ID,
			&i.SuppressionListID,
			&i.RegionName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppressionRevenueSizesByListID = `-- name: GetSuppressionRevenueSizesByListID :many
SELECT id, suppression_list_id, revenue_range, created_at, updated_at
FROM suppression_revenue_sizes
WHERE suppression_list_id = $1
ORDER BY revenue_range ASC
`

func (q *Queries) GetSuppressionRevenueSizesByListID(ctx context.Context, suppressionListID uuid.UUID) ([]SuppressionRevenueSize, error) {
	rows, err := q.db.QueryContext(ctx, getSuppressionRevenueSizesByListID, suppressionListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuppressionRevenueSize
	for rows.Next() {
		var i SuppressionRevenueSize
		if err := rows.Scan(
			&i.ID,
			&i.SuppressionListID,
			&i.RevenueRange,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppressionStatesByListID = `-- name: GetSuppressionStatesByListID :many
SELECT id, suppression_list_id, state_name, created_at, updated_at
FROM suppression_states
WHERE suppression_list_id = $1
ORDER BY state_name ASC
`

func (q *Queries) GetSuppressionStatesByListID(ctx context.Context, suppressionListID uuid.UUID) ([]SuppressionState, error) {
	rows, err := q.db.QueryContext(ctx, getSuppressionStatesByListID, suppressionListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuppressionState
	for rows.Next() {
		var i SuppressionState
		if err := rows.Scan(
			&i.ID,
			&i.SuppressionListID,
			&i.StateName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
