// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: suppliers.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (tenant_id, name, contact_email)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, contact_email, api_key, is_active, created_at, updated_at
`

type CreateSupplierParams struct {
	TenantID     uuid.UUID
	Name         string
	ContactEmail sql.NullString
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, createSupplier, arg.TenantID, arg.Name, arg.ContactEmail)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSupplierUser = `-- name: CreateSupplierUser :one
INSERT INTO supplier_users (tenant_id, supplier_id, user_id)
VALUES ($1, $2, $3)
RETURNING tenant_id, supplier_id, user_id
`

type CreateSupplierUserParams struct {
	TenantID   uuid.UUID
	SupplierID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) CreateSupplierUser(ctx context.Context, arg CreateSupplierUserParams) (SupplierUser, error) {
	row := q.db.QueryRowContext(ctx, createSupplierUser, arg.TenantID, arg.SupplierID, arg.UserID)
	var i SupplierUser
	err := row.Scan(&i.TenantID, &i.SupplierID, &i.UserID)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM suppliers WHERE id = $1 AND tenant_id = $2
`

type DeleteSupplierParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteSupplier(ctx context.Context, arg DeleteSupplierParams) error {
	_, err := q.db.ExecContext(ctx, deleteSupplier, arg.ID, arg.TenantID)
	return err
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, tenant_id, name, contact_email, api_key, is_active, created_at, updated_at FROM suppliers WHERE id = $1 AND tenant_id = $2
`

type GetSupplierByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetSupplierByID(ctx context.Context, arg GetSupplierByIDParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, getSupplierByID, arg.ID, arg.TenantID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierForUser = `-- name: GetSupplierForUser :one
SELECT supplier_id
FROM supplier_users
WHERE user_id = $1
`

func (q *Queries) GetSupplierForUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getSupplierForUser, userID)
	var supplier_id uuid.UUID
	err := row.Scan(&supplier_id)
	return supplier_id, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, tenant_id, name, contact_email, api_key, is_active, created_at, updated_at FROM suppliers
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSuppliersParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.QueryContext(ctx, listSuppliers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ContactEmail,
			&i.ApiKey,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name = $3,
    contact_email = $4,
    api_key = $5,
    is_active = $6,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, contact_email, api_key, is_active, created_at, updated_at
`

type UpdateSupplierParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	ContactEmail sql.NullString
	ApiKey       sql.NullString
	IsActive     sql.NullBool
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, updateSupplier,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ContactEmail,
		arg.ApiKey,
		arg.IsActive,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSupplierStatus = `-- name: UpdateSupplierStatus :exec
UPDATE suppliers SET is_active = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateSupplierStatusParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	IsActive sql.NullBool
}

func (q *Queries) UpdateSupplierStatus(ctx context.Context, arg UpdateSupplierStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSupplierStatus, arg.ID, arg.TenantID, arg.IsActive)
	return err
}
