// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    tenant_id,
    email,
    password_hash,
    role,
    invited,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
RETURNING id, tenant_id, email, password_hash, role, is_active, invited, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	Invited      sql.NullBool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Invited,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Invited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
  AND tenant_id = $2
`

type DeleteUserParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteUser, arg.ID, arg.TenantID)
	return err
}

const getTenantAdminEmail = `-- name: GetTenantAdminEmail :one
SELECT contact_email
FROM tenants
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTenantAdminEmail(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTenantAdminEmail, id)
	var contact_email sql.NullString
	err := row.Scan(&contact_email)
	return contact_email, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, role, is_active, invited, created_at, updated_at
FROM users
WHERE email = $1
  AND tenant_id = $2
LIMIT 1
`

type GetUserByEmailParams struct {
	Email    string
	TenantID uuid.UUID
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Invited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, role, is_active, invited, created_at, updated_at
FROM users
WHERE id = $1
  AND tenant_id = $2
LIMIT 1
`

type GetUserByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Invited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, password_hash, role, is_active, invited, created_at, updated_at
FROM users
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context, tenantID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.Invited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserInviteStatus = `-- name: UpdateUserInviteStatus :one
UPDATE users
SET invited = $3, updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, email, password_hash, role, is_active, invited, created_at, updated_at
`

type UpdateUserInviteStatusParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Invited  sql.NullBool
}

func (q *Queries) UpdateUserInviteStatus(ctx context.Context, arg UpdateUserInviteStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserInviteStatus, arg.ID, arg.TenantID, arg.Invited)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Invited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $3, updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, email, password_hash, role, is_active, invited, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.ID, arg.TenantID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Invited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $3, updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, email, password_hash, role, is_active, invited, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Role     string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.ID, arg.TenantID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Invited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET is_active = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateUserStatusParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	IsActive sql.NullBool
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.ID, arg.TenantID, arg.IsActive)
	return err
}

const updateUserStatusBySupplier = `-- name: UpdateUserStatusBySupplier :exec
UPDATE users
SET is_active = $1, updated_at = NOW()
WHERE id IN (
    SELECT user_id
    FROM supplier_users
    WHERE supplier_id = $2
)
`

type UpdateUserStatusBySupplierParams struct {
	IsActive   sql.NullBool
	SupplierID uuid.UUID
}

func (q *Queries) UpdateUserStatusBySupplier(ctx context.Context, arg UpdateUserStatusBySupplierParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusBySupplier, arg.IsActive, arg.SupplierID)
	return err
}
